"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var apollo_server_core_1 = require("apollo-server-core");
var UserTypeDefs = apollo_server_core_1.gql(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n\n    extend type Query {\n        getUser(id: String!): UserType\n        getUsers(sort: SortInputType, searchs: [SearchInputType]): [UserType]\n        getSelf: UserType\n    }\n\n    extend type Mutation {\n        register(email: EmailAddress!, password: String!, detail: UserInputType): UserType\n        updateUser(id: String!, roles: [String]!, detail: UserInputType!): UserType\n        updateSelf(detail: UserInputType!): UserType\n        deleteUser(id: String!): String\n    }\n\n    type UserType {\n        id: String\n        email: EmailAddress\n        firstName: String\n        lastName: String\n        avatar: String\n        dateOfBirth: DateTime\n        gender: GenderType\n        address: String\n        phoneNumber: String\n        createdAt: DateTime\n        updatedAt: DateTime\n    }\n\n    input UserInputType {\n        firstName: String\n        lastName: String\n        avatar: Upload\n        dateOfBirth: DateTime\n        gender: GenderType\n        address: String\n        phoneNumber: String\n    }\n\n    enum GenderType {\n        MALE\n        FEMALE\n    }\n"], ["\n\n    extend type Query {\n        getUser(id: String!): UserType\n        getUsers(sort: SortInputType, searchs: [SearchInputType]): [UserType]\n        getSelf: UserType\n    }\n\n    extend type Mutation {\n        register(email: EmailAddress!, password: String!, detail: UserInputType): UserType\n        updateUser(id: String!, roles: [String]!, detail: UserInputType!): UserType\n        updateSelf(detail: UserInputType!): UserType\n        deleteUser(id: String!): String\n    }\n\n    type UserType {\n        id: String\n        email: EmailAddress\n        firstName: String\n        lastName: String\n        avatar: String\n        dateOfBirth: DateTime\n        gender: GenderType\n        address: String\n        phoneNumber: String\n        createdAt: DateTime\n        updatedAt: DateTime\n    }\n\n    input UserInputType {\n        firstName: String\n        lastName: String\n        avatar: Upload\n        dateOfBirth: DateTime\n        gender: GenderType\n        address: String\n        phoneNumber: String\n    }\n\n    enum GenderType {\n        MALE\n        FEMALE\n    }\n"])));
exports.default = UserTypeDefs;
var templateObject_1;
